# Generated by Django 3.0.8 on 2020-08-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200816_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogary',
            new_name='catogory',
        ),
    ]
