# Generated by Django 3.0.8 on 2020-08-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200816_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogory',
            new_name='category',
        ),
    ]
